[tool.poetry]
name = "chatgpt-dev"
version = "0.1.0"
description = ""
authors = ["Kekele <esinamdemanya@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torchvision = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
